name: FirstAPI Local
values:
  - key: baseUrl
    value: 'http://localhost:5114'
    enabled: true
    type: default
  - key: token
    value: ''
    enabled: true
    type: default
  - key: userId
    value: '1'
    enabled: true
    type: default
  - key: todoId
    value: '1'
    enabled: true
    type: default
