@FirstAPI_HostAddress = http://localhost:5114
@FirstAPI_UserEndpoint = {{FirstAPI_HostAddress}}/api/user

GET {{FirstAPI_UserEndpoint}}/

###

GET {{FirstAPI_UserEndpoint}}/1

###
POST {{FirstAPI_UserEndpoint}}
Content-Type: application/json

{
    "id": 5,
    "name": "Slava",
    "age": 91
}

###

DELETE {{FirstAPI_UserEndpoint}}/2

###

GET {{FirstAPI_UserEndpoint}}/adults