@FirstAPI_HostAddress = http://localhost:5114
@FirstAPI_UserEndpoint = {{FirstAPI_HostAddress}}/api/user

GET {{FirstAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{FirstAPI_HostAddress}}/api/user/2

###
POST {{FirstAPI_HostAddress}}/api/user
Content-Type: application/json

{
    "id": 2,
    "name": "Yarik",
    "age": 25
}

###

DELETE {{FirstAPI_HostAddress}}/api/user/2